### ISSUE TITLE
Move react to peerDependencies

### ISSUE THREAD

**Issue by lxe** [uber/r-dom#15]
Browserified bundles double-up on react instances, even for semver-comatible things.

cc @ross-

**Comment by lxe** [comment]
Same as #14

**Comment by lxe** [comment]
Example of when things will break without peerDeps:

```
$ npm ls react                                                                                                                                                                 
my-project@1.0.0 /Users/aleksey/devel/my-project
├─┬ r-dom@1.0.0
│ └── react@0.12.2
└── react@0.12.1
```

**Comment by Raynos** [comment]
@lxe just use `npm dedupe`

**Comment by lxe** [comment]
@Raynos npm dedupe fails for whatever reason :(

```
npm WARN unavoidable conflict Not de-duplicating
npm WARN unavoidable conflict react { '/Users/aleksey/devel/.../node_modules/r-dom/node_modules/react': '0.12.2',
npm WARN unavoidable conflict   '/Users/aleksey/devel/.../node_modules/react': '0.12.1' }
```

**Comment by Raynos** [comment]
@lxe because the https://github.com/uber/r-dom/blob/master/package.json#L37 range is too aggressive.

r-dom should just downgrade the version of react it uses to `^0.12.0`

**Comment by lxe** [comment]
@Raynos I still live in a world of tildes in npm semvers. Thank you.

**Comment by rtsao** [comment]
Fixed by https://github.com/uber/r-dom/pull/29
